import { StyleSheet } from 'react-native';

import { fonts } from '@/constants/typography';

export const incomingOfferStyles = StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
  },
  fallbackBg: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F172A',
  },
  scrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.32)',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 22,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  timerTrack: {
    flex: 1,
    height: 6,
    borderRadius: 99,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
  },
  timerFill: {
    height: 6,
    borderRadius: 99,
  },
  timerText: {
    fontFamily: fonts.extraBold,
    fontSize: 14,
    color: '#111827',
    width: 36,
    textAlign: 'right',
  },
  timerUrgent: {
    color: '#EF4444',
  },
  expiringBanner: {
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  expiringText: {
    fontFamily: fonts.bold,
    fontSize: 13,
    color: '#B91C1C',
    textAlign: 'center',
  },
  kicker: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  payout: {
    marginTop: 4,
    fontFamily: fonts.extraBold,
    fontSize: 36,
    color: '#111827',
    letterSpacing: -1,
  },
  payoutSub: {
    marginTop: 4,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#6B7280',
  },
  incentiveRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  incentiveChip: {
    backgroundColor: '#ECFDF5',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  incentiveChipText: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#047857',
  },
  meta: {
    marginTop: 8,
    marginBottom: 16,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#4B5563',
  },
  routeBlock: {
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    padding: 14,
    gap: 14,
    marginBottom: 4,
  },
  etaBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EEF2FF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  etaBannerLabel: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#4F46E5',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  etaBannerValue: {
    fontFamily: fonts.extraBold,
    fontSize: 15,
    color: '#312E81',
  },
  etaBannerMuted: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#6366F1',
  },
  pinBlock: {
    flexDirection: 'row',
    gap: 12,
  },
  pinDotYou: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#6366F1',
    marginTop: 5,
  },
  pinDotPickup: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#EA4B14',
    marginTop: 5,
  },
  pinDotDrop: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2563EB',
    marginTop: 5,
  },
  pinCopy: {
    flex: 1,
  },
  pinLabel: {
    fontFamily: fonts.semiBold,
    fontSize: 11,
    color: '#9CA3AF',
    textTransform: 'uppercase',
  },
  pinKm: {
    marginTop: 2,
    fontFamily: fonts.bold,
    fontSize: 13,
    color: '#C2410C',
  },
  pinKmMuted: {
    marginTop: 2,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#9CA3AF',
  },
  pinValue: {
    marginTop: 2,
    fontFamily: fonts.bold,
    fontSize: 15,
    color: '#111827',
  },
  pinAddr: {
    marginTop: 2,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#6B7280',
  },
  actions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  declineBtn: {
    flex: 1,
    height: 54,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  declineText: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: '#111827',
  },
  acceptBtn: {
    flex: 1.4,
    height: 54,
    borderRadius: 16,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptText: {
    fontFamily: fonts.extraBold,
    fontSize: 16,
    color: '#FFFFFF',
  },
});
